export CFLAG
CFLAG = -Wall
CFLAG += -c
CFLAG += -D_BSD
CFLAG += -D_WITH_DPRINTF

include ../scripts/msg.mk
include ../scripts/tools.mk


all: libsoccr.a
.PHONY:	all

target := soccr.o

libsoccr.a: $(target)
	$(AR) rsc $@ $^

.PHONY:	test
test:
	$(GNUMAKE) -e -C soccrtest

%.o: %.c 
	$(call msg-cc, $@)
	$(Q) $(CC) $(INCLUDE) $(CFLAG) -o $@ $^


clean:
	$(GNUMAKE) -C soccrtest clean
	$(RM) soccr.o
	$(RM) libsoccr.a
.PHONY:	clean

