COMPELFLAG := -fpie
ASFLAG := -c
ASFLAG += -Wstrict-prototypes
ASFLAG += -D__ASSEMBLY__
ASFLAG += -nostdlib
ASFLAG += -fomit-frame-pointer
ASFLAG += -fno-stack-protector

parasite += writecall.o
parasite += syscall.o
parasite += parasite-head.o

INCLUDE := -I ../

parasite-head: $(parasite) ../compel-pack.lds.S
	$(LD) -pie $(parasite) -o $@ -T ../compel-pack.lds.S

%.o: %.S
	$(CC) $(INCLUDE) $(COMPELFLAG) $(ASFLAG) -o $@ $^

%.o: %.c
	$(CC) $(INCLUDE) $(COMPELFLAG) $(CFLAG) -o $@ $^
